version: '3.7'
services:
  jobmanager:
    image: flink:1.14.4-scala_2.12-java11
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager

  taskmanager:
    image: flink:1.14.4-scala_2.12-java11
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      - KAFKA_CREATE_TOPICS=click:1:1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_PORT=9092
#      - KAFKA_HOST_NAME=0.0.0.0
#      - HOSTNAME_COMMAND=hostname
      - KAFKA_BROKER_ID=1
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - ALLOW_PLAINTEXT_LISTENER=yes
  zookeeper:
    image: zookeeper:3.8.1
    ports:
      - "22181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

#  pulsar:
#    image: apachepulsar/pulsar:2.9.1
#    container_name: pulsar
#    ports:
#      - "8080:8080"
#      - "6650:6650"
#    environment:
#      PULSAR_MEM: " -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
##      - PULSAR_MEM=" -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g -Dpulsar.auth.basic.conf=/pulsar/conf/.htpasswd"
#      systemTopicEnabled: "true"
#      topicLevelPoliciesEnabled: "true"
#      transactionCoordinatorEnabled: "true"
##      - authenticationEnabled=true
##      - authorizationEnabled=true
##      - authenticationProviders=org.apache.pulsar.broker.authentication.AuthenticationProviderBasic
##      - superUserRoles=super
##      - brokerClientAuthenticationPlugin=org.apache.pulsar.client.impl.auth.AuthenticationBasic
##      - brokerClientAuthenticationParameters={\"userId\":\"super\",\"password\":\"superpass\"}
#    command: >
#      /bin/bash -c
#      " bin/apply-config-from-env.py conf/standalone.conf
#      && bin/pulsar standalone"

